name: Long Running Test Monitor

on:
  schedule:
    - cron: '0 */4 * * *' # every 4 hours
  push:
    branches:
      - master
  pull_request: # TODO: remove this before merging
    branches:
      - master

env:
  BIGQUERY_DATASET: dev_src_flow_test_metrics # TODO: update to production table before merging
  BIGQUERY_TABLE: skipped_tests

jobs:
  upload-long-running-test-summary:
    name: Upload Long Running Test Summary
    strategy:
      fail-fast: false
      matrix:
        test-category:
          - unit # currently, this is the only category with long running tests
    env:
      RUN_ID: ${{ github.run_id }}
      TEST_CATEGORY: ${{ matrix.test-category }}
      SKIP_REASON: TEST_LONG_RUNNING
    runs-on: ubuntu-latest
    steps:
    - name: Get job run date
      id: job_run_date
      run: echo "::set-output name=date::$(TZ=":America/Los_Angeles" date -Iseconds)"
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Checkout repo
      uses: actions/checkout@v2

